services:
  ai-text-editor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3300:3300'
    environment:
      - NODE_ENV=production
      - PORT=3300
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
